### ISSUE TITLE
Highlighted Text Invisible

### ISSUE THREAD

**Issue by seanogdev** [henrikdahl/hyperterm-base16-ocean-saturated#10]
Hi Henrik,

Having a minor issue where highlighted text is invisible. Its mostly prominent when I paste in text but also an issue in headers inside nano, when for example changing settings. If I highlight the text with my cursor I can see it but obviously thats not the best solution

Non highlighted header

https://www.dropbox.com/s/7kdl108af7011jc/Screenshot%202016-10-10%2013.39.14.png?dl=0

Highlighted

https://www.dropbox.com/s/nwazaeh2lbjthay/Screenshot%202016-10-10%2013.39.24.png?dl=0

Is there something wrong with my Hyper configuration? I just installed Hyper a few days ago and this is the only plugin I have installed :)

**Comment by henrikruscon** [comment]
Hey Miralize!

I can't seem to replicate your issue. Have you tried restarting HyperTerm? It's usually the cause for visual issues. Since I see your header is faulty as well.

Otherwise, I'll look into this later today ✌️

Glad you like my plugin 👊

**Comment by rob-moore** [comment]
Hey all. I'm running into this issue too. I've done everything from restarting, reinstalling and removing all my plugins. All of my highlighted text is invisible.

http://imgur.com/a/tNte1

**Comment by rob-moore** [comment]
@miralize I was able to get this issue fixed for pasting to the command line by installing the `hyperterm-paste` plugin.

However my nano highlighted text is still invisible.

**Comment by henrikruscon** [comment]
HyperTerm changed how it handles pasted content. It only sets the background-color while it previously would set the color to backgroundColor as well.

<img width="284" alt="skarmavbild 2016-12-07 kl 16 49 02" src="https://cloud.githubusercontent.com/assets/1430576/20974637/3343f34e-bc9d-11e6-8851-87c85669d2d3.png">

Seeing as HyperTerm has to fix this themselves eventually, it might not be worth looking into a temporary fix on my side. Looks like @rob-moore found a way through another plugin until then. ✌️
