### ISSUE TITLE
The X is duplicated in Hyper

### ISSUE THREAD

**Issue by controversial** [henrikdahl/hyperterm-base16-ocean-saturated#11]
Hyper (the new version of HyperTerm) has a slightly changed header tab structure, which was put in place to allow full transparency. As part of this change, the Xs seem to be duplicated when using this theme. To reproduce: hover the close part of a tab using this theme in Hyper

**Comment by henrikruscon** [comment]
Sorry for the delay. I've been swamped with work. I've finally got spare time again. Thanks for letting me know. I've pushed a version that fixes this issue. ✌️
