### ISSUE TITLE
Theme breaks tab background

### ISSUE THREAD

**Issue by structief** [henrikdahl/hyperterm-base16-ocean-saturated#13]
After installing theme through `hpm` and hitting Cmd+Shft+R (Full reload), everything seems fine. However, after quitting Hyper, and firing it up again, tabs are transparent.
![screen shot 2016-12-13 at 17 14 46](https://cloud.githubusercontent.com/assets/7501293/21148175/b40ed8a4-c157-11e6-992c-39a2431beabe.png)

**Comment by henrikruscon** [comment]
Hyper keeps changing a lot with every update and they just pushed an update that broke my theme.

I'll fix it asap. ✌️

**Comment by henrikruscon** [comment]
@kliptonize Just pushed an update that should fix every issue. Let me know if I've missed something. 👋

**Comment by Florian95** [comment]
@henrikdahl I just install it and I have the same error. Last version of Hyper, and this plugins used : 
```
  plugins: [
    "hyperterm-1password",
    "hyperterm-tab-icons",
    "hyperterm-alternatescroll",
    "hyperlinks",
    "hyper-statusline",
    "hyperterm-base16-ocean-saturated"
  ],
```

Thank you for your work !

**Comment by henrikruscon** [comment]
@Florian95 Try commenting out the theme and launch Hyper, then uncomment it and launch Hyper again. Does it solve it?

Otherwise, what's your Hyper version and OS?

Thanks for the kind words 👊

**Comment by Florian95** [comment]
It's good only in the same window where I uncomment the theme. If I launch a new one, nothing... 

MacOS 10.12.1
Hyper 1.0.1 (1.0.1.1369)

**Comment by Florian95** [comment]
@henrikdahl Any news about this bug ? How can I help ?

Thank you.

**Comment by henrikruscon** [comment]
@Florian95 sorry, didn't know it was still an issue.

What's your plugin list? ✌️

**Comment by Florian95** [comment]
My plugins : 

```
  plugins: [
    "hyperterm-1password",
    "hyperterm-tab-icons",
    "hyperterm-alternatescroll",
    "hyperlinks",
    "hyperterm-base16-ocean-saturated"
  ],
```

**Comment by henrikruscon** [comment]
@Florian95 

Name of plugin was changed to `hyper-oceans16` to match the new naming convention of Hyper. Additionally the tabs were separated into its own plugin for the ability to use them with any theme https://github.com/henrikdahl/hyper-tabs-enhanced

Would you mind trying these to see if it solves it for you? ✌️
