### ISSUE TITLE
Similar theme for Vim?

### ISSUE THREAD

**Issue by benoror** [henrikdahl/hyperterm-base16-ocean-saturated#5]
@henrikdahl this theme is great! kudos! I was wondering if you know of a (similar) version of it for Vim?

Thanks, cheers mate!

**Comment by henrikruscon** [comment]
@benoror Thanks, glad to hear that!

I don't know much about vim. I don't personally use it. I could support it if someone guides me through what it's currently missing. 😁

If you're merely looking for a similar syntax then base16-darkspace-ocean syntax scheme should be fairly close. ✌️

**Comment by benoror** [comment]
Something like https://chriskempson.github.io/base16/#ocean ?

**Comment by henrikruscon** [comment]
@benoror Started working on vim support 👋

![vim](https://cloud.githubusercontent.com/assets/1430576/18302107/09c208b2-74d6-11e6-94eb-03e6ef80a1a8.png)

**Comment by benoror** [comment]
@henrikdahl Wowwww! Kudos! 👏 👏 Let me know as soon as you upload it to a repo

**Comment by benoror** [comment]
My vim needs some color ❤️ 
![screen shot 2016-09-07 at 12 07 51](https://cloud.githubusercontent.com/assets/119117/18321480/c1752fbc-74f3-11e6-9e3b-346b07818bed.png)

**Comment by benoror** [comment]
@henrikdahl I'm getting to strange issues with Vim:

1) Fat ugly icon after switching from insert mode to normal mode
2) Line chopped when using Emoji

![screen shot 2016-09-07 at 17 37 30](https://cloud.githubusercontent.com/assets/119117/18331107/19829108-7522-11e6-9d09-7350cebd080a.png)

**Comment by controversial** [comment]
@henrikdahl Any progress?

**Comment by benoror** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by controversial** [comment]
Sorry @benoror — really just wondering whether this is still planned, not whether there has actually been tangible progress.

**Comment by henrikruscon** [comment]
@controversial @benoror It's nearly done. Been overloaded with work within my company. I'll resume as soon as I've got spare time again ✌️

**Comment by controversial** [comment]
Ok. I could try to help if you want, but otherwise just keep us posted.

**Comment by henrikruscon** [comment]
Sorry for the massive delay. I simply don't have time to finish this. I'll close this for now. Sorry to disappoint! ✌️
