### ISSUE TITLE
Wrong window icons

### ISSUE THREAD

**Issue by benoror** [henrikdahl/hyperterm-base16-ocean-saturated#6]
I'm getting this in OS X

<img width="258" alt="screen shot 2016-09-04 at 12 15 05" src="https://cloud.githubusercontent.com/assets/119117/18232625/49d5bf50-7299-11e6-89e7-b50a0217f52b.png">

**Comment by henrikruscon** [comment]
Force quit and start it up again and it should be fine ✌️

**Comment by benoror** [comment]
That did the trick, thx!
