### ISSUE TITLE
Make file explorer path separate module

### ISSUE THREAD

**Issue by drschwabe** [henrikdahl/hyperterm-base16-ocean-saturated#9]
Hey there, great theme.  Particularly like the 'open file explorer / path feature' along the bottom.  It would be awesome if that was available as it's own plugin. 

I scoured npm for a similar plugin but it seems your theme(s) have the only implementation available so far.

https://github.com/henrikdahl/hyperterm-base16-ocean-saturated/blob/master/index.js#L410

**Comment by henrikruscon** [comment]
Hey, thanks!

Glad you like it, I personally use it all the time, I couldn't do without that feature. ✌️

Are you suggesting the bottom status line should be a plugin on its own? Would the git branch also be included or would it be an option? 👋

**Comment by drschwabe** [comment]
Yeah me too that feature is killer, without it I was constantly having to type "setsid nemo ." from terminal which opens my file browser to the cwd; a single click is much nicer. 

Yes, the bottom status row should be a plugin on it's own so that it can work with any other theme. 

Personally, I don't mind the git branch/status in there too but for those who have zsh it may be redundant so perhaps you could work towards a 'config technique' as you eldued to in my other issue to let the user toggle that on/off. 

Another thing you could break it into three modules to accommodate ideas for this 'statusfooter' that other people might want to put there.  Ex: 

hyperterm-statusfooter
hyperterm-statusfooter-filebrowserpath
hyperterm-statusfooter-git

then theoretically, from other authors: 
hyperterm-statusfooter-weather
hyperterm-statusfooter-cputemp

With this in mind, just wondering if hyperterm has a procedure for plugins to 'require' other plugins...

**Comment by controversial** [comment]
I think that bottom bar should definitely become a separate plugin.

**Comment by henrikruscon** [comment]
Sorry for the massive delay. I've been swamped with work but I've finally got some spare time. I separated the status line from the themes and made it into its own plugin.

https://github.com/henrikdahl/hyper-statusline

It takes its colors from the current theme so you can use other themes than mine. I'm still considering expanding features such as more detailed git status in a future update.

Let me know what you think. 👋✌️

**Comment by kmax1189** [comment]
Looks great!

**Comment by controversial** [comment]
Looks awesome! I'll try it out tonight.

**Comment by drschwabe** [comment]
Brilliant! Thanks for putting in the effort to separate this feature into it's own module.

**Comment by henrikruscon** [comment]
Thanks for the feedback!

@drschwabe Ay, thanks! Let me know if you're missing any config options 👊

**Comment by drschwabe** [comment]
Ok, since you asked :)  Specifying a specific file browser would be great; ie- the one that opens when you click on the path.  

For example, on Ubuntu clicking your path opens Nautilus which is the default file browser.  However, many users have another file browser installed ie- Nemo, which they may prefer instead. 

On a different system, I had hacked your original theme to open Nemo instead but have since formatted; I believe it was just a matter of replacing the environment variable you are using with the string "nemo" in this case.   A config option would be ideal of course.

**Comment by henrikruscon** [comment]
What's the protocol? Simply `nemo://` instead of `file://`?

**Comment by drschwabe** [comment]
No worries, I simply changed default file browser from Nautilus to Nemo as per: http://www.fandigital.com/2013/01/set-nemo-default-file-manager-ubuntu.html
